exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/pages-themes/primer"

  remote_theme: pages-themes/primer@v0.6.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Welcome to Amarthya page!
description: Amarthya Achmadi
